apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-gitops-argocd-edge
  namespace: default
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-gitops-argocd-edge
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: edge-repo
                  namespace: openshift-gitops
                  labels:
                    argocd.argoproj.io/secret-type: repository
                stringData:
                  type: git
                  url: https://github.com/AshrafHassan-RH/ai-core.git
                  password: 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
                  username: not-used
          pruneObjectBehavior: DeleteIfCreated
          severity: low
          remediationAction: enforce
