apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: install-quay
  namespace: default
  annotations:
    policy.open-cluster-management.io/categories: T-Mobile Standard Operators
    policy.open-cluster-management.io/standards: Infra Standard workload 
    policy.open-cluster-management.io/controls: Baseline Configuration
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: quay-operator-product-sub-1
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: quay-operator
                  namespace: openshift-operators
                spec:
                  name: quay-operator
                  channel: stable-3.11
                  installPlanApproval: Automatic
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: quay-operator-status-1
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: ClusterServiceVersion
                metadata:
                  namespace: openshift-operators
                spec:
                  displayName: Red Hat Quay
                status:
                  phase: Succeeded
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: registry-1
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: quay.redhat.com/v1
                kind: QuayRegistry
                metadata:
                  name: devregistry
                  namespace: openshift-operators
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: registry-status-1
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: quay.redhat.com/v1
                kind: QuayRegistry
                metadata:
                  namespace: openshift-operators
                status:
                  currentVersion: v3.11.0               
