apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-install-web-terminal
  namespace: default
  annotations:
    policy.open-cluster-management.io/categories: Web-Terminal
    policy.open-cluster-management.io/standards: Web-Terminal
    policy.open-cluster-management.io/controls: Web-Terminal
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: web-terminal-operator-ns
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: openshift-operators
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: web-terminal-operator-operator-group
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  name: web-terminal-operator
                  namespace: openshift-terminal
                spec:
                  targetNamespaces:
                    - openshift-operators
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: web-terminal-operator-subscription
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  labels:
                    operators.coreos.com/web-terminal.openshift-operators: ''
                  name: web-terminal
                  namespace: openshift-operators
                spec:
                  channel: fast
                  installPlanApproval: Manual
                  name: web-terminal
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace
                  startingCSV: web-terminal.v1.7.0-0.1684429884.p
